name: GitlabSync

on:
  - push
  - delete
 

jobs:
  sync:
    name: Git Repo Sync
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout code
    - uses: action/git-repo-sync@v2
    - run: git push -u origin main http://www.192.168.99.66.com/hariomdso/helloworld.git
    
      env:
        # Such as https://github.com/wangchucheng/g
        target-url: ${{ secrets.TARGET_URL }}
        # Such as wangchucheng
        target-username: ${{ secrets.TARGET_USERNAME }}
          # You can store token in your project's 'Setting > Secrets' and reference the name here. Such as ${{ secrets.ACCESS\_TOKEN }}
        target-token: ${{ secrets.TARGET_TOKEN }}
