name: GitlabSync

on:
  - push
  - delete
 

jobs:
  sync:
    name: Git Repo Sync
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: push the code
      uses: 3SDVA/git-repo-sync@v3
      with:
        # Such as https://github.com/wangchucheng/g
        target-url: http://www.192.168.99.66.com/hariomdso/helloworld.git
        # Such as wangchucheng
        target-username: hariomdso
          # You can store token in your project's 'Setting > Secrets' and reference the name here. Such as ${{ secrets.ACCESS\_TOKEN }}
        target-token: ksSsHBjTEb_ZRPyLJ2N3
